### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'signame'

### ISSUE THREAD

**Issue by PKatarina** [citiususc/construe#10]
Hello, 
I have used construe_environment.yml to create the proper environment and while running the example script it gives me the error:
FileNotFoundError: [Errno 2] No such file or directory: 'signame' 

I  probably didn't installed something properly, but I can't figure it out. 
If you need any extra info, please let me know

**Comment by tomas-teijeiro** [comment]
I'm sorry you are having trouble running the software :disappointed: 

Please make sure that you have installed the WFDB software package: https://physionet.org/content/wfdb/10.7.0/. You should be able to run the command `signame` in the command line.

**Comment by PKatarina** [comment]
Hi, thanks. This resolved the issue!
