### ISSUE TITLE
example missing some records.

### ISSUE THREAD

**Issue by lkjell** [citiususc/construe#3]
In run_example.sh it says:

>     Reproduces the interpretation process for a given figure in the paper,
>     automatically choosing the proper parameters for fragment_processing.py.
> 
>     All record fragments are under the examples/ directory, with a name
>     corresponding to the appropriate figure in the paper, from fig1 to fig10.

However, in the example folder fig1, fig2, and fig7 is missing.

**Comment by tomas-teijeiro** [comment]
If you check the paper, you can see that figures 1, 2 and 7 do not show any ECG fragment, so they cannot be interpreted by Construe.
