### ISSUE TITLE
add_constaint of same variable

### ISSUE THREAD

**Issue by lkjell** [citiususc/construe#5]
The `add_constraint` method in `ConstraintNetwork` does not appear adding a constraint when the `Variable` input are the same.

**Comment by tomas-teijeiro** [comment]
I am not sure what you mean, since the beginning of the method is intended to deal with the case when the two variables are the same.
```
if va is vb:
    if not const.zero_in:
        raise InconsistencyError('Constraints between the same '
                                          'variable must contain zero')
```

**Comment by lkjell** [comment]
Yes it only check. But it does not add a constraint to the network. Calling get_constraints() will not give anything new.
I thought that if `va.start == 0, va.end == 10` then `add_constraint(va,va, Interval(0,5))` would restrict `va.end` to 5?

**Comment by tomas-teijeiro** [comment]
Ok, I understand now. Maybe it is a bit complicated to get it, but constraints only bound the **difference** between two variables. If the variable is the same, then there is no need to include any constraint, since the difference will always be 0. If you want to limit the value of a variable `va` to the interval `(0, 5)`, then you should define a reference variable `v0` with value `(0, 0)` and `add_constraint(v0, va, Interval(0, 5))`.

**Comment by lkjell** [comment]
so constraint Interval(a, b) means that |va.start - vb.start| in [a, b] and |va.end - vb.end| in [a, b] ?

**Comment by tomas-teijeiro** [comment]
You have to think that a variable has a single value on a particular domain, and constraints are used to delimit the range of possible values based on values of other variables. In general, `va ∊ (-∞, ∞)`, but by adding a constraint `(va, vb, Interval(a, b))` you impose that `a ≤ vb-va ≤ b`. Then, after constraint propagation by network minimization, the possible limits for the variables may be reduced, and that is the meaning of `v.start` and `v.end`.

I recommend you to take a look at this paper to understand the theory in greater depth: Dechter, R., Meiri, I., & Pearl, J. (1991). Temporal constraint networks. *Artificial intelligence*, 49(1-3), 61-95.
